## IMU config
#
# autocalibrate:      tare and calibrate all imus when initializing node
# dev_names:          string identifier to find configs for each device (NOTE: list dongle devices first)
# dev_type:           YEI device type (only DNG and WL supported for now)
# imu_mode:           wireless or wired (only needed for WL devices)
# broadcast:          switch on broadcast mode, to get data from all connected IMUs
# streaming:          switch on streaming mode (faster), all following parameters in us
# streaming_delay:    amount of time the sensor will wait before outputting the first packet of streaming data
# streaming_duration: length of the streaming session (NOTE: 'unlimited' is 0xFFFFFFFF, see manual)
# streaming_interval: how often data will be output (0 = every filter loop, other values must be > 1000)
# wired_port:         port address for device when wired
# streaming_slots:	  defines what information each device is streaming
# wireless_dng:       name of dongle associated to this WL device (must have configured dongle wireless table)
# wireless_id:        logical id of WL device in associated dongle's wireless table

autocalibrate: true

## 1 Wired streaming test ##
#dev_names: ['pedal']
#dev_type: {'pedal': 'WL'}
#imu_mode: {'pedal': 'wired'}
#broadcast: false
#streaming: true
#streaming_interval: 0
#streaming_duration: 'unlimited'
#streaming_delay: 0
#streaming_slots: {'pedal': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState']}
#wired_port: {'pedal': '/dev/ttyACM0'}

## 2 Wired streaming test ##
# dev_names: ['pedal', 'remote']
# dev_type: {'pedal': 'WL', 'remote': 'WL'}
# imu_mode: {'pedal': 'wired', 'remote': 'wired'}
# broadcast: false
# streaming: true
# streaming_interval: 0
# streaming_duration: 'unlimited'
# streaming_delay: 0
# streaming_slots: {'pedal': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState'], 'remote': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState']}
# wired_port: {'pedal': '/dev/ttyACM1', 'remote': '/dev/ttyACM2'}

## 1 Wireless streaming test ##
dev_names: ['pc', 'angle']
dev_type: {'pc': 'DNG', 'angle': 'WL'}
imu_mode: {'angle': 'wireless'}
broadcast: false
streaming: true
streaming_interval: 0
streaming_duration: 'unlimited'
streaming_delay: 0
streaming_slots: {'angle': ['getTaredOrientationAsQuaternion']}
wired_port: {'pc': '/dev/ttyACM0'}
wireless_dng: {'angle': 'pc'}
wireless_id: {'angle': 1}

## 2 Wireless streaming test - stateMachineSingleLeg.py setup ##
#dev_names: ['pc', 'lowerLeg', 'upperLeg']
#dev_type: {'pc': 'DNG', 'lowerLeg': 'WL', 'upperLeg': 'WL'}
#imu_mode: {'lowerLeg': 'wireless', 'upperLeg': 'wireless'}
#broadcast: false
#streaming: false
#streaming_interval: 0
#streaming_duration: 'unlimited'
#streaming_delay: 0
#streaming_slots: {'lowerLeg': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState'], 'upperLeg': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState']}
#wired_port: {'pc': '/dev/ttyACM0'}
#wireless_dng: {'lowerLeg': 'pc', 'upperLeg': 'pc'}
#wireless_id: {'lowerLeg': 1, 'upperLeg': 7}

## 4 Wireless streaming test - record.py setup ##
#dev_names: ['pc', 'body','lowerLeg', 'upperLeg', 'foot']
#dev_type: {'pc': 'DNG', 'body': 'WL','lowerLeg': 'WL', 'upperLeg': 'WL', 'foot': 'WL'}
#imu_mode: {'body': 'wireless','lowerLeg': 'wireless', 'upperLeg': 'wireless', 'foot': 'wireless'}
#broadcast: false
#streaming: true
#streaming_interval: 0
#streaming_duration: 'unlimited'
#streaming_delay: 0
#streaming_slots: {'body': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState'], 'lowerLeg': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState'], 'upperLeg': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState'], 'foot': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState']}
#wired_port: {'pc': '/dev/ttyACM0'}
#wireless_dng: {'body': 'pc', 'lowerLeg': 'pc', 'upperLeg': 'pc', 'foot': 'pc'}
#wireless_id: {'body': 3,'lowerLeg': 1, 'upperLeg': 2, 'foot': 7}


## 4 Wireless streaming test - stateMachine.py setup ##
#dev_names: ['pc', 'lowerRightLeg', 'upperRightLeg', 'lowerLeftLeg', 'upperLeftLeg']
#dev_type: {'pc': 'DNG', 'lowerRightLeg': 'WL', 'upperRightLeg': 'WL', 'lowerLeftLeg': 'WL', 'upperLeftLeg': 'WL'}
#imu_mode: {'lowerRightLeg': 'wireless', 'upperRightLeg': 'wireless', 'lowerLeftLeg': 'wireless', 'upperLeftLeg': 'wireless'}
#broadcast: false
#streaming: true
#streaming_interval: 0
#streaming_duration: 'unlimited'
#streaming_delay: 0
#streaming_slots: {'lowerRightLeg': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState'], 'upperRightLeg': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState'], 'lowerLeftLeg': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState'], 'upperLeftLeg': ['getTaredOrientationAsQuaternion', 'getNormalizedGyroRate', 'getButtonState']}
#wired_port: {'pc': '/dev/ttyACM0'}
#wireless_dng: {'lowerRightLeg': 'pc', 'upperRightLeg': 'pc', 'lowerLeftLeg': 'pc', 'upperLeftLeg': 'pc'}
#wireless_id: {'lowerRightLeg': 3, 'upperRightLeg': 7, 'lowerLeftLeg': 1, 'upperLeftLeg': 2}